name: 'Upload artifact'
description: 'Upload artifacts to our S3 deployment bucket'
inputs:
  project-name:
    description: 'Name of the project to upload'
    required: true
  version: 
    description: 'Version of the project to upload'
    required: false
  path:
    description: 'Path to folder that should be uploaded'
    required: true
  aws-access-key-id:
    required: true
    description: 'AWS access key ID'
  aws-secret-access-key:
    required: true
    description: 'AWS secret access key'
  aws-artifact-bucket:
    required: true
    description: 'Bucket that AWS artifact should be stored in'
runs:
  using: "composite"
  steps:
    - name: Rename (replace special chars with dash)
      shell: bash
      run: echo "ARTIFACT_NAME=$(echo ${{ inputs.version }} | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV

    - name: Zip
      shell: bash
      run: (cd ${{ inputs.path }} && zip -r ${{ env.ARTIFACT_NAME }}.zip .)

    - run: aws s3 cp ${{ inputs.path }}/${{ env.ARTIFACT_NAME }}.zip s3://${{ inputs.aws-artifact-bucket }}/github-actions/tfso/${{ inputs.project-name }}/${{ env.ARTIFACT_NAME }}.zip
      shell: bash
      name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: 'eu-west-1'
    
    - run: rm ${{ inputs.path }}/${{ env.ARTIFACT_NAME }}.zip
      shell: bash
      name: Remove artifact