name: 'Upload artifact'
description: 'Upload artifacts to our S3 deployment bucket'
inputs:
  project-name:
    description: 'Name of the project to upload'
    required: true
  version: 
    description: 'Version of the project to upload'
    required: false
  path:
    description: 'Path to folder that should be uploaded'
    required: true
runs:
  using: "composite"
  steps:
    - uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ${{ inputs.version }}.zip ${{ inputs.path }}

    - run: aws s3 sync ${{ inputs.path }} s3://${{ secrets.AWS_ARTIFACT_BUCKET }}/github-actions/tfso/${{ inputs.project-name }}/${{ inputs.version }}.zip
      shell: bash
      name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'